Traceback (most recent call last):
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/book/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from cenpy import products
acs = products.ACS(2019)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/6m/lbbbs2n90xq6lk5v5902brkc0000gq/T/ipykernel_794/1023165891.py[0m in [0;36m?[0;34m()[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mcenpy[0m [0;32mimport[0m [0mproducts[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0macs[0m [0;34m=[0m [0mproducts[0m[0;34m.[0m[0mACS[0m[0;34m([0m[0;36m2019[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/miniconda3/envs/book/lib/python3.12/site-packages/cenpy/__init__.py[0m in [0;36m?[0;34m()[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mexplorer[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mfrom[0m [0;34m.[0m[0mremote[0m [0;32mimport[0m [0mAPIConnection[0m [0;32mas[0m [0m_APIConnection[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;32mfrom[0m [0;34m.[0m[0mtools[0m [0;32mimport[0m [0m_load_sitekey[0m[0;34m,[0m [0mset_sitekey[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0;32mfrom[0m [0;34m.[0m[0mproducts[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0mSITEKEY[0m [0;34m=[0m [0m_load_sitekey[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m

[0;32m/opt/miniconda3/envs/book/lib/python3.12/site-packages/cenpy/products.py[0m in [0;36m?[0;34m()[0m
[1;32m      8[0m [0;32mimport[0m [0mnumpy[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;32mimport[0m [0mcopy[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0m_places[0m [0;34m=[0m [0m_ft[0m[0;34m([0m[0;34m"place"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0m_places[0m[0;34m[[0m[0;34m"TARGETFP"[0m[0;34m][0m [0;34m=[0m [0m_places[0m[0;34m.[0m[0mPLACEFP[0m[0;34m.[0m[0mapply[0m[0;34m([0m[0;32mlambda[0m [0mx[0m[0;34m:[0m [0mstr[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m.[0m[0mrjust[0m[0;34m([0m[0;36m5[0m[0;34m,[0m [0;34m"0"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     13[0m [0m_places[0m[0;34m[[0m[0;34m"TARGETNAME"[0m[0;34m][0m [0;34m=[0m [0m_places[0m[0;34m.[0m[0mPLACENAME[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m [0m_places[0m[0;34m[[0m[0;34m"STATEFP"[0m[0;34m][0m [0;34m=[0m [0m_places[0m[0;34m.[0m[0mSTATEFP[0m[0;34m.[0m[0mapply[0m[0;34m([0m[0;32mlambda[0m [0mx[0m[0;34m:[0m [0mstr[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m.[0m[0mrjust[0m[0;34m([0m[0;36m2[0m[0;34m,[0m [0;34m"0"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m [0m_places[0m[0;34m.[0m[0mdrop[0m[0;34m([0m[0;34m[[0m[0;34m"PLACEFP"[0m[0;34m,[0m [0;34m"FUNCSTAT"[0m[0;34m,[0m [0;34m"COUNTY"[0m[0;34m,[0m [0;34m"PLACENAME"[0m[0;34m][0m[0;34m,[0m [0minplace[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/miniconda3/envs/book/lib/python3.12/site-packages/pandas/core/generic.py[0m in [0;36m?[0;34m(self, name)[0m
[1;32m   6295[0m             [0;32mand[0m [0mname[0m [0;32mnot[0m [0;32min[0m [0mself[0m[0;34m.[0m[0m_accessors[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6296[0m             [0;32mand[0m [0mself[0m[0;34m.[0m[0m_info_axis[0m[0;34m.[0m[0m_can_hold_identifiers_and_holds_name[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6297[0m         [0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6298[0m             [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 6299[0;31m         [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'PLACEFP'

